<div class="container-login h-100">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <form class="box" method="post" action="/authenticateAdministracao">
                    <h1>Escola TB</h1>
                    <h2>Espaço Administração</h2>
                    <input type="text" name="email" placeholder="E-mail">
                    <input type="password" name="senha" placeholder="Senha">
                    <?php if($this->view->login == 'error'){?>
                        <div class="row">
                            <div class="col">
                                <span class="text text-danger">*E-mail e ou senha inválido(s)</span>
                            </div>
                        </div>
                    <?php }?>
                    <input type="submit" name="" value="Login" href="#">
                </form>
            </div>
        </div>
    </div>
</div>