<nav class="navbar navbar-expand navbar-dark bg-dark">
    <h1 class="navbar-brand" >Administração</h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/administracaoHome"></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/sair">Sair <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<div>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Criar novo Aluno</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Criar novo Professor</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Criar novo Adm</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Update Aluno</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Update Professor</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Update Adm</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Deletar Aluno</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Deletar Professor</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#"> Deletar Adm</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Consulta Aluno</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Consulta Professor</a>
    </button>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Consulta Adm</a>
    </button>
    <br>

</div>