<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Aluno</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/alunoHome"></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/sair">Sair <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<div>
    <br>
    <button type="button" class="btn-lg btn-block">
        <a href="#">Consulta Notas</a>
    </button>
    <br>
</div>