<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Aluno</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/administracaoHome"></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="/sair">Sair <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<br>
<div class="row h-100 justify-content-center align-items-center">
    <form action="/criarAluno" method="post">
        <div class="row ">
            <div class="col">
                <input type="text"  name="fname" class="form-control" placeholder="Nome">
            </div>
            <div class="col">
                <input type="text" name="lname"  class="form-control" placeholder="Sobrenome">
            </div>
        </div>
        <br>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Email</label>
                <input type="email" name="email" class="form-control" id="inputEmail4" placeholder="Email">
            </div>
            <div class="form-group col-md-6">
                <label for="inputPassword4">Senha</label>
                <input type="password"  name="senha" class="form-control" id="inputPassword4" placeholder="Senha">
            </div>
            <div class="form-group col-md-6">
                <label for="inputCpf">CPF</label>
                <input type="text"  name="cpf" class="form-control cpf-mask" placeholder="Ex.: 000.000.000-00">
            </div>
            <div class="form">
                <h5>Sexo</h5>
                <select class="form-control" ">
                    <option selected>Escolher...</option>
                    <option>Masculino</option>
                    <option>Feminino</option>
                </select>
            </div>
            <div class="form-group col-md-6">
                <label for="inputData">Data</label>
                <input id="date" name="dataNacimento" type="date"  ">
            </div>
            <div class="form-group col-md-6">
                <label for="inputCpf">Telefone</label>
                <input type="text"  name="dd" class="form-control cel-sp-mask" placeholder="Ex.: DDD -> (00) ">
                <input type="text" name="numero" class="form-control cel-sp-mask" placeholder="Ex.: 00000-0000">
                <select name="tipoTelefone" class="form-control">
                    <option selected>Tipo Telefone</option>
                    <option>CEL</option>
                    <option>FIX</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <label for="inputAddress">Endereço</label>
            <input type="text" name="endereco" class="form-control" id="inputAddress" placeholder="Rua dos Bobos, nº 0">
        </div>
        <div class="form-group">
            <label for="inputAddress2">Bairro</label>
            <input type="text"  name="bairro" class="form-control" id="inputAddress2" placeholder="Apartamento, hotel, casa, etc.">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputCity">Cidade</label>
                <input type="text" name="cidade"  class="form-control" id="inputCity">
            </div>
            <div class="form-group col-md-4">
                <label for="inputEstado">Estado</label>
                <select   id="inputEstado"  name="estado" class="form-control">
                    <option selected>Escolher...</option>
                    <option>PA</option>
                </select>
            </div>
            <br>
            <button class="btn btn-primary" type="submit">Enviar</button>
    </form>
</div>