<nav class="navbar navbar-expand navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Professor</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample02">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Inicio <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#"></a>
            </li>
            <li class="nav-item active">
                <a class="nav-link" href="#">Sair <span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>
<br>
<div class="row h-100 justify-content-center align-items-center">
    <form action="#" method="post">
        <div class="row ">
            <div class="col">
                <input type="text" class="form-control" placeholder="Nome">
            </div>
            <div class="col">
                <input type="text" class="form-control" placeholder="Sobrenome">
            </div>
        </div>
        <br>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label for="inputEmail4">Email</label>
                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
            </div>
            <div class="form-group col-md-6">
                <label for="inputPassword4">Senha</label>
                <input type="password" class="form-control" id="inputPassword4" placeholder="Senha">
            </div>
            <div class="form-group col-md-6">
                <label for="inputCpf">Formação</label>
                <input type="text" class="form-control cpf-mask" placeholder="Ex.: Matematica">
            </div>
            <div class="form-group col-md-6">
                <label for="inputCpf">Telefone</label>
                <input type="text" class="form-control cel-sp-mask" placeholder="Ex.: DDD -> (00) ">
                <input type="text" class="form-control cel-sp-mask" placeholder="Ex.: 00000-0000">
                <select class="form-control">
                    <option selected>Tipo Telefone</option>
                    <option>CEL</option>
                    <option>FIX</option>
                </select>
            </div>
        </div>
        <button class="btn btn-primary" type="submit">Enviar</button>
    </form>
</div>  